This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file ./phd thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file phd thesis.acn....done (204 entries accepted, 0 rejected).
Sorting entries.....done (1737 comparisons).
Generating output file phd thesis.acr....done (149 lines written, 0 warnings).
Output written in phd thesis.acr.
Transcript written in phd thesis.alg.
